### PR TITLE
Fix migration redundancies

### PR DESCRIPTION
**Pull request by nickhartdev**
#### What's this PR do?
- fixes conflicts within the set of migrations that we had, the database is now up to date where we left off
#### Where should the reviewer start?  
Start with the first migration.
#### How should this be manually tested?
Run `knex migrate:latest` - it should run without any issues now
#### Any background context you want to provide?
The conflicts were happening because of some redundancies that are now eliminated! More actual updates to come now.
#### What are the relevant tickets?
None!
#### Screenshots (if appropriate)
DANCE

### CODE REVIEW

**Review by Abdeboskey — APPROVED** [review]
I'm glad you were able to figure this out! I'd definitely be into walking through the fix together at some point. Thank you!!

**Review by carlymclift — APPROVED** [review]
Nice work on this! thanks Nick

**Review by GreysonElkins — APPROVED** [review]
This looks good! @nickhartdev did you check if this is seeding properly? I'll def be diggin into this one deeper tomorrow, assuming I missed some catch-up on the issue today and want to touch base with you and the team before I get rolling!

**Comment by Abdeboskey** [comment]
@Greyson, we didn't quite touch base about this, I think the plan was to
have Nick walk us through when we get started tomorrow 👍🏼

**Comment by greyson** [comment]
@GreysonElkins I think he meant to tag you, since I have nothing to do with this project :)

**Pull request merged**
